version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    image: mysql
    container_name: mountain_searcher_DB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mountain_searcher
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes: 
      - ./mysql/:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mountain-searcher_default
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    tty: true
    command: go run .
    volumes:
      - .:/go/src/projects/mountain-searcher
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mountain_searcher_DB
    networks:
      - mountain-searcher_default

volumes:
  mysql:
    name: mountain_searcher_volume

networks:
  mountain-searcher_default:
    external: true